// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ajiawzsujkkqzntuvrjc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFqaWF3enN1amtrcXpudHV2cmpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwODkxMjAsImV4cCI6MjA2MzY2NTEyMH0.flu6QGvrxlVjO3f2FwYV1cB_HUZrUuFxeDVKlT1mprE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);